#Training
#eval-only
learning_rate: 0
batch_size: 16
weight_decay: 0
lr_decay: 1
epochs: 1
train_2d: False

# whether to use accumulate gradients
accumulate_grads: False
accumulate_iters: 1

# Model
model_name: MixSTE

in_chans: 2
embed_dim_ratio: 512
depth: 8
num_heads: 8
mlp_ratio: 2.
qkv_bias: True
qk_scale: null
drop_path_rate: 0.1
n_frames: 243 # 243 if add_velocity is False else 242

# Data
data_root: data1/motion3d/
data_root_2d: data1/motion2d/
subset_list: [ MultipleDetectedImages_243_27 ]
dt_file: h36m_sh_cpn_hrnet_yolo_misc.pkl
detector_type: cpn
num_joints: 17
root_rel: True # Normalizing joints relative to the root joint
add_velocity: False
disable_joints_2_5d: True

# Loss
lambda_3d_velocity: 0.0
lambda_scale: 0.0
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
use_proj_as_2d: False
flip: True